pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'SDCycleScrollView'#图片轮播器
pod 'MBProgressHUD'
pod 'Mantle'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell'
pod 'ScreenCompatible_LFL'#分辨率适配